apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
  type: ClusterIP
